config:
  events:
    can:
      drop : false
      pickup: false
      place: false
      break: false
      pvp: NEVER
  hotbar:
    vanish: true
    examine: true
    freeze: true
    stafflist: true
    random: true
  commands:
    freeze: true
    punish: true
    playertp: true
    examine: true
    stafflist: true
    staff: true